FROM node:alpine
WORKDIR /app
COPY ./client/package.json ./package.json
COPY ./client/package-lock.json ./package-lock.json
COPY ./client/public ./public
COPY ./client/src ./src
RUN npm i
EXPOSE 3000
CMD ["npm", "run", "start"]
